#!/bin/sh

# Install dot files into user's home directory

# Files to exclude from symlinking
is_excluded() {
  case "$1" in
    install|Rakefile|CLAUDE.md|verify.rb)
      return 0
      ;;
    README*)
      return 0
      ;;
    *.swp)
      return 0
      ;;
  esac
  return 1
}

replace_all=false

link_file() {
  local file=$1
  echo "linking ~/.${file}"
  ln -s "$PWD/$file" "$HOME/.$file"
}

replace_file() {
  local file=$1
  rm "$HOME/.$file"
  link_file "$file"
}

for file in *; do
  is_excluded "$file" && continue

  target="$HOME/.$file"

  if [[ -e "$target" || -L "$target" ]]; then
    if $replace_all; then
      replace_file "$file"
    else
      printf "overwrite ~/.%s? [ynaq] " "$file"
      read -r response
      case $response in
        a)
          replace_all=true
          replace_file "$file"
          ;;
        y)
          replace_file "$file"
          ;;
        q)
          exit
          ;;
        *)
          echo "skipping ~/.$file"
          ;;
      esac
    fi
  else
    link_file "$file"
  fi
done

if [[ -d $HOME/Library/Preferences/ ]]; then
    ln -s ~/.config/clangd $HOME/Library/Preferences/clangd
    echo "linking $HOME/Library/Preferences/clangd"
fi

